[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
clap = { version = "4.1.13", features = ["derive"] }
delay_timer = "0.11.4"
env_logger = "0.10.0"
log = "0.4.17"
