[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
clap = { version = "4.1.13", features = ["derive"] }
env_logger = "0.10.0"
tokio = { version = "1.27.0", features = ["full"] }
tokio-cron-scheduler = "0.9.4"
