services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./timetables.db:/app/timetables.json
      - ./backend.log:/app/backend.log
